defmodule HivefinWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :hivefin

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_hivefin_key",
    signing_salt: "fhi/v8P0",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :hivefin,
    gzip: not code_reloading?,
    only: HivefinWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Bundled jellyfin-web UI (official Android app WebView loads server root).
  # Docker builds populate priv/jellyfin-web; missing files pass through to router.
  plug Plug.Static,
    at: "/",
    from: {:hivefin, "priv/jellyfin-web"},
    gzip: false,
    brotli: false

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :hivefin
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Jellyfin Vue / other SPAs call the API from a different origin.
  plug HivefinWeb.Plugs.CORS

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  # Normalize /system/info/public → /System/Info/Public before routing
  plug HivefinWeb.Plugs.NormalizeJellyfinPath
  plug HivefinWeb.Router
end

